language: php

php:
  - 5.4

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script: bin/phpunit --coverage-text

after_script:
  - bin/phpcs -v --report=summary --standard=PSR1,PSR2 Main/ Hasher/ Tests/
